### ISSUE TITLE
Segmentation Fault on Debian 12.1

### ISSUE THREAD

**Issue by bbx-github** [tinyops-ru/zabbix-lld-ws#2]
There is really not a whole lot I can give you here. It just crashes immediately. Any help is appreciated.

**Comment by lebe-dev** [comment]
@bbx-github thank you for feedback, I'll be back with results :)

**Comment by lebe-dev** [comment]
@bbx-github Rebuilded linux release in another way, please try and let me know

https://github.com/tinyops-ru/zabbix-lld-ws/releases/download/0.7.0/wszl-v0.7.0-linux-static.zip

**Comment by bbx-github** [comment]
Thank you, that seemed to work! No more segementation faults. I will try to figure out the rest
