### ISSUE TITLE
Log level switching not supported or wrongly documented

### ISSUE THREAD

**Issue by bbx-github** [tinyops-ru/zabbix-lld-ws#3]
./wszl gen --log-level=debug
error: Found argument '--log-level' which wasn't expected, or isn't valid in this context
./wszl gen --log-level debug
error: Found argument '--log-level' which wasn't expected, or isn't valid in this context

Either the documentation is wrong or it is not implemented

**Comment by lebe-dev** [comment]
The proper usage is:

```shell
wszl --log-level=debug ...
```

Updated README. This is how clap library implemented.

**Comment by bbx-github** [comment]
Yes, this works thank you!
