### ISSUE TITLE
Vhost item gets skipped if web scenario exists but trigger does not

### ISSUE THREAD

**Issue by bbx-github** [tinyops-ru/zabbix-lld-ws#5]
If for some reason creating a trigger did not work but creating a web scenario did, the site will be skipped the next time it runs because it seems that only the web scenario is checked. If I remove the web scenarios as well it will run again.

```
...
DEBUG - [zabbix_lld_ws] - item: Vhost https://mysite.net item
DEBUG - [zabbix_lld_ws] - - url 'https://mysite.net'
DEBUG - [zabbix_lld_ws] - web scenario has been found for url 'mysite.net', skip
...
```

**Comment by lebe-dev** [comment]
Thanks for report, let me check.

**Comment by lebe-dev** [comment]
Please check new version:

https://github.com/tinyops-ru/zabbix-lld-ws/releases/tag/0.7.1

**Comment by bbx-github** [comment]
Thanks, this works. But it will exit with `2023-09-29 14:56:09 - INFO - [zabbix_lld_ws] - web scenarios and triggers have been created` even when every single trigger fails. Just an FIY :) I will close the issue since the functionality is there now

**Comment by lebe-dev** [comment]
Thanks for testing, agree the message little bit confusing so it will be removed in next build.
