### ISSUE TITLE
Feature Request - Configure wszl without using vhdt, providing a list of URL's

### ISSUE THREAD

**Issue by tpancz** [tinyops-ru/zabbix-lld-ws#6]
I am not sure if this is the right area, I am new to github so my apologies.
My vhosts are spread out across a lot of VM's, so I use 1 Zabbix proxy to monitor many web scenarios.
It would be a great addition if we could provide a list like this: (just an example, I'm not sure the best way to implement this)

```
{ "data": [
	{
		"{#PORT}": "443",
		"{#DOMAIN}": "google.ca",
	},
	{
		"{#PORT}": "5061",
		"{#DOMAIN}": "github.com",
	}
]}
```

When wszl is executed, it would create web scenarios for the listed URLs.
The wszl.yml would still provide the information for trigger and scenario.

Thanks.

**Comment by lebe-dev** [comment]
I think the plain text format would be better (one url per row):

```
google.ca
github.com
```

If you able to generate LLD JSON you will able to generate plain text file. LLD JSON has different structure in Zabbix <4.x and 4.x+

**Comment by lebe-dev** [comment]
Status update: work in progress

**Comment by lebe-dev** [comment]
Status update: testing

**Comment by lebe-dev** [comment]
Status update: integration with `zabbix-api` crate (https://github.com/lebe-dev/zabbix-api-rs)

**Comment by lebe-dev** [comment]
Status update: testing

**Comment by lebe-dev** [comment]
@tpancz new version release https://github.com/tinyops-ru/zabbix-lld-ws/releases/tag/0.8.0

**Comment by tpancz** [comment]
Apologies for the delay in testing this on my end. I believe I am having package issues due to using Debian 12.

```
user@proxy-zabbix-01:/etc/zabbix# ./wszl -d /etc/zabbix gen --source=file --file=urls.txt
./wszl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./wszl)
```


And here is another output showing 2.36 as the highest version for Deb 12. I'm not sure if it's possible to update this with the risk of bricking my proxy.

```
user@proxy-zabbix-01:/etc/zabbix# lsb_release -a; uname -a; apt-cache policy `dpkg -l | grep glib | awk {'print $2'}`

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
Linux proxy-zabbix-01 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
glibc-doc:
  Installed: 2.36-9+deb12u4
  Candidate: 2.36-9+deb12u4
  Version table:
 *** 2.36-9+deb12u4 500
        500 http://mirror.csclub.uwaterloo.ca/debian bookworm/main amd64 Packages
        500 http://security.debian.org/debian-security bookworm-security/main amd64 Packages
        100 /var/lib/dpkg/status
glibc-source:
  Installed: 2.36-9+deb12u4
  Candidate: 2.36-9+deb12u4
  Version table:
 *** 2.36-9+deb12u4 500
        500 http://mirror.csclub.uwaterloo.ca/debian bookworm/main amd64 Packages
        500 http://security.debian.org/debian-security bookworm-security/main amd64 Packages
        100 /var/lib/dpkg/status
```


I am just posting this for an update, I don't expect you to do any more work on this. I'll keep looking for a solution.

**Comment by lebe-dev** [comment]
Let me check and I will come back with details.

**Comment by lebe-dev** [comment]
A new build:

https://github.com/tinyops-ru/zabbix-lld-ws/releases/tag/0.8.0

**Comment by tpancz** [comment]
Everything worked up to this point:

```
2024-03-15 15:39:14 - INFO - [zabbix_api::client::v6] - creating trigger 'Site 'https://google.ca' is unavailable' with expression 'proxy-zabbix-01:web.test.fail[Check index page 'https://google.ca'].last()'..
2024-03-15 15:39:14 - ERROR - [zabbix_api::client::v6] - ZabbixError { code: -32602, message: "Invalid params.", data: "Invalid parameter \"/1/expression\": incorrect expression starting from \"proxy-zabbix-01:web.test.fail[Check index page 'https://google.ca'].last()\"." }
2024-03-15 15:39:14 - ERROR - [zabbix_lld_ws::cli] - generation error: zabbix api call error
2024-03-15 15:39:14 - ERROR - [zabbix_lld_ws::cli] - [zabbix error] code -32602, message 'Invalid params.', data: 'Invalid parameter "/1/expression": incorrect expression starting from "proxy-zabbix-01:web.test.fail[Check index page 'https://google.ca'].last()".' [/zabbix error]
```

What worked for me was taken from tests/wszl.yml and using this:

`    value: "last(/${HOST}/web.test.fail[Check index page '${URL}'])<>0"
`

Not sure if it is a version issue but I have it working now. Thank you.

**Comment by lebe-dev** [comment]
I think it just syntax issue for zabbix triggers. Please, close the issue if it done.
